//@version=5
indicator(title="Directional Movement Index", shorttitle="DMI", format=format.price, precision=4)

// Input Parameters
lensig = input.int(14, title="DMI Smoothing", minval=1)  // Smoothing period for ADX
len = input.int(14, minval=1, title="DMI Length")  // Length for DMI calculation

// Directional Movement Calculation
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)

// True Range and Directional Indicators
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)

// ADX Calculation
sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)

// Plotting the ADX and DI lines
plot(adx, color=#F50057, title="ADX")
plot(plus, color=#2962FF, title="+DI")
plot(minus, color=#FF6D00, title="-DI")
