//@version=5
indicator(title="Moving Average Convergence Divergence", shorttitle="MACD", timeframe="", timeframe_gaps=true)

// Getting inputs
place_on_list = input.bool(title = "Place On The List", defval = true)
fast_length = input.int(title = "MACD Fast Length", defval = 12, minval = 1)
slow_length = input.int(title = "MACD Slow Length", defval = 26, minval = 1)
signal_length = input.int(title = "MACD Signal Length", defval = 9, minval = 1, maxval = 50)

// Calculating
fast_ma = ta.ema(close, fast_length)  // Defaulting to EMA for the fast MA
slow_ma = ta.ema(close, slow_length)  // Defaulting to EMA for the slow MA
macd = fast_ma - slow_ma
signal = ta.ema(macd, signal_length)  // Defaulting to EMA for the signal line
hist = macd - signal

// Alerts (must remain in global scope)
alertcondition(hist[1] >= 0 and hist < 0, title = 'Rising to falling', message = 'The MACD histogram switched from a rising to falling state')
alertcondition(hist[1] <= 0 and hist > 0, title = 'Falling to rising', message = 'The MACD histogram switched from a falling to rising state')

// Control visibility based on `Place On The List`
plot_hist = place_on_list ? hist : na
plot_macd = place_on_list ? macd : na
plot_signal = place_on_list ? signal : na

// Plotting
hline(0, "Zero Line", color = color.new(#787B86, 50))
plot(plot_hist, title = "Histogram", style = plot.style_columns, color = (hist >= 0 ? (hist[1] < hist ? #26A69A : #B2DFDB) : (hist[1] < hist ? #FFCDD2 : #FF5252)))
plot(plot_macd, title = "MACD", color = #2962FF)
plot(plot_signal, title = "Signal", color = #FF6D00)
